/* ==========================================================
   E-COMMERCE ORDERS ANALYSIS
     Purpose:
       Analyze order performance, customer behavior,
       product sales, payment methods, coupon usage,
       and referral channel effectiveness.
   ========================================================== */


-- ==========================================================
-- 1. Dataset Overview
-- ==========================================================

-- Count unique orders and customers
SELECT
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS total_customers
FROM orders;

-- Review order distribution by status
SELECT
    order_status,
    COUNT(order_id) AS order_count
FROM orders
GROUP BY order_status
ORDER BY order_count DESC;


-- ==========================================================
-- 2. Overall Sales Performance
-- ==========================================================

-- Calculate key sales metrics excluding cancelled orders
SELECT
    COUNT(order_id) AS total_orders,
    SUM(total_price) AS total_order_amount,
    MIN(total_price) AS minimum_order_value,
    MAX(total_price) AS maximum_order_value,
    AVG(unit_price) AS average_unit_price,
    SUM(quantity) AS total_quantity_sold
FROM orders
WHERE order_status != 'Cancelled';


-- ==========================================================
-- 3. Revenue Trend Analysis
-- ==========================================================

-- Annual revenue performance
SELECT
    YEAR(order_date) AS sales_year,
    SUM(total_price) AS total_revenue
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY YEAR(order_date)
ORDER BY total_revenue DESC;

-- Year-over-Year (YoY) revenue growth analysis
WITH yearly_sales AS (
    SELECT
        YEAR(order_date) AS sales_year,
        SUM(total_price) AS total_revenue
    FROM orders
    WHERE order_status != 'Cancelled'
    GROUP BY YEAR(order_date)
)
SELECT
    sales_year,
    total_revenue,
    LAG(total_revenue) OVER (ORDER BY sales_year) AS previous_year_revenue,
    ROUND(((total_revenue - LAG(total_revenue) OVER (ORDER BY sales_year)) * 100.0)
        /
        NULLIF(LAG(total_revenue) OVER (ORDER BY sales_year), 0),
        2) AS yoy_growth_percent
FROM yearly_sales
ORDER BY sales_year;


-- ==========================================================
-- 4. Customer Analysis
-- ==========================================================

-- Top 10 customers by spending
SELECT TOP 10
    customer_id,
    SUM(total_price) AS total_spent
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY customer_id
ORDER BY total_spent DESC;


-- ==========================================================
-- 5. Product Performance Analysis
-- ==========================================================

-- Number of orders by product
SELECT
    product,
    COUNT(order_id) AS order_count
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY product
ORDER BY order_count DESC;

-- Revenue generated by product
SELECT
    product,
    SUM(total_price) AS total_revenue
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY product
ORDER BY total_revenue DESC;

-- Average quantity purchased per product
SELECT
    product,
    AVG(quantity) AS average_quantity
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY product
ORDER BY average_quantity DESC;


-- ==========================================================
-- 6. Payment Method Analysis
-- ==========================================================

-- Order volume by payment method
SELECT
    payment_method,
    COUNT(order_id) AS total_orders
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY payment_method
ORDER BY total_orders DESC;

-- Revenue by payment method
SELECT
    payment_method,
    SUM(total_price) AS total_revenue
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY payment_method
ORDER BY total_revenue DESC;


-- ==========================================================
-- 7. Coupon Performance Analysis
-- ==========================================================

-- Orders generated by coupon code
SELECT
    coupon_code,
    COUNT(order_id) AS total_orders
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY coupon_code
ORDER BY total_orders DESC;

-- Revenue generated by coupon code
SELECT
    coupon_code,
    SUM(total_price) AS total_revenue
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY coupon_code
ORDER BY total_revenue DESC;


-- ==========================================================
-- 8. Referral Source Analysis
-- ==========================================================

-- Orders generated by referral source
SELECT
    referral_source,
    COUNT(order_id) AS total_orders
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY referral_source
ORDER BY total_orders DESC;

-- Revenue generated by referral source
SELECT
    referral_source,
    SUM(total_price) AS total_revenue
FROM orders
WHERE order_status != 'Cancelled'
GROUP BY referral_source
ORDER BY total_revenue DESC;
